# -*- coding: utf-8 -*-
"""helper_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6ZoBsH2TEeIYiw9IoJiCAjAMN60TgQP
"""

import numpy as np


def bass_model(t, p, q, M):
    """Bass Diffusion Model for the annual sales"""
    return (M * (p + q)**2 * np.exp(-(p + q) * t)) / ((p + q * np.exp(-(p + q) * t))**2)