# -*- coding: utf-8 -*-
"""script1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V3_6gvAiXfi6rAh0Mhr4LEMXJeOLMOqQ
"""

import numpy as np
import pandas as pd
from scipy.optimize import curve_fit
import matplotlib
import matplotlib.pyplot as plt


from helper_functions import bass_model

data = {
    'Year': [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024],
    'Sales': [15, 35, 60, 114, 85, 82, 75, 66]
}

airpods = pd.DataFrame(data)
airpods

plt.figure(figsize=(8,4))

plt.bar(airpods['Year'], airpods['Sales'], color='pink', alpha=0.6)

plt.plot(airpods['Year'], airpods['Sales'], marker='o', color='blue', linewidth=2)

plt.title('Apple AirPods Unit Sales(2017-2024)')

plt.xlabel('Year')

plt.ylabel('Unit Sales in Milions')

plt.show()
def bass_model(t, p, q, M):
    """Bass Diffusion Model for the annual sales"""
    return (M * (p + q)**2 * np.exp(-(p + q) * t)) / ((p + q * np.exp(-(p + q) * t))**2)


airpods['Year_norm'] = airpods['Year'] - airpods['Year'].min()


initial_guess = [0.03, 0.38, 160]
parameters, _ = curve_fit(
    bass_model,
    airpods['Year_norm'],
    airpods['Sales'],
    p0=initial_guess
)
p, q, M = parameters


print("\nBass Model Parameters for Apple AirPods:")
print(f"coefficient of innovation(p): {p:.4f}")
print(f"coefficient of imitation(q): {q:.4f}")
print(f"market potential in millions(M): {M:.2f}")