# -*- coding: utf-8 -*-
"""script2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Jgy91ayme_87k5u5v0J2Y_HpYBtv6-N
"""

import numpy as np
import pandas as pd
from scipy.optimize import curve_fit
import matplotlib
import matplotlib.pyplot as plt


from helper_functions import bass_model

dyson_market_potential = M * 0.05

years_future_dyson = np.arange(0, 20)  #We will predict 20 years from the release date of Dyson OnTrac headphones.

predicted_dyson = bass_model(years_future_dyson, p, q, dyson_market_potential)

years_calendar_dyson = np.array(range(2025, 2025 + len(years_future_dyson)))
dyson_adoption_df = pd.DataFrame({
    'Year': years_calendar_dyson,
    'Yearly Adoption of Dyson': predicted_dyson,
    'Cumulative Adoption of Dyson': np.cumsum(predicted_dyson)
})

print("\nForecasted Adoption for Dyson OnTrac:")
print(dyson_adoption_df.round(2))


plt.figure(figsize=(10, 6))

#Here, we will plot the yearly adoption.
plt.subplot(2, 1, 1)
plt.plot(years_calendar_dyson, predicted_dyson, marker='o', color='pink')

plt.title('Forecasted Yearly Adoption of Dyson OnTrac headphones')

plt.xlabel('Year')

plt.ylabel('Yearly Adoption')
plt.xticks(years_calendar_dyson)
plt.grid(True)

#And here we will plot the cumulative adoption.

plt.subplot(2, 1, 2)
plt.plot(years_calendar_dyson, np.cumsum(predicted_dyson), marker='o', color='blue')

plt.title('Forecasted Cumulative Adoption of Dyson OnTrac headphones')

plt.xlabel('Year')

plt.ylabel('Cumulative Adoption')
plt.xticks(years_calendar_dyson)
plt.grid(True)

plt.tight_layout()
plt.show()